version: '3.2'
services:
    grafana:
        container_name: grafana
        restart: unless-stopped
        image: grafana/grafana
        ports:
            - '3000:3000'
        volumes:
            - /var/lib/grafana:/var/lib/grafana
        links:
            - influxdb
    influxdb:
        container_name: influxdb
        restart: unless-stopped
        image: influxdb:latest
        ports:
            - '8086:8086'
        volumes:
            - /var/lib/influxdb:/var/lib/influxdb
